server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/pokedex
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pokedex